### ISSUE TITLE
Unable to cast object of type 'System.String' to type 'System.DateTime' - EntityFramework, Mysql

### ISSUE THREAD

**Issue by shadowvzs** [shadowvzs/reactivities#1]
- EntityFrameWorkCore v3.0.1
- MySql  Ver 14.14 Distrib 5.7.29, for Linux (x86_64) using  EditLine wrapper

>  System.InvalidCastException: Unable to cast object of type 'System.String' to type 'System.DateTime'.
>    at MySqlConnector.Core.Row.GetDateTime(Int32 ordinal) in C:\projects\mysqlconnector\src\MySqlConnector\Core\Row.cs:line 331
>    at MySql.Data.MySqlClient.MySqlDataReader.GetDateTime(Int32 ordinal) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 251
>    at lambda_method(Closure , QueryContext , DbDataReader , ResultContext , Int32[] , ResultCoordinator )
>    at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
>    at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
>    at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
>    at Application.Activities.List.Handler.Handle(Query request, CancellationToken cancellationToken) in /home/Application/Activities/List.cs:line 72
 
[link to file](https://github.com/shadowvzs/reactivities/blob/master/Reactivities/Application/Activities/List.cs)
```csharp

var queryable = _context.Activities
	.Where(x => x.Date >= request.StartDate)
	.OrderBy(x => x.Date)
	.AsQueryable();

if (request.IsGoing && !request.IsHost) {
	queryable = queryable.Where(x => x.UserActivities.Any(a => 
		a.AppUser.UserName == _userAccessor.GetCurrentUsername()));
}

if (!request.IsGoing && request.IsHost) {
	queryable = queryable.Where(x => x.UserActivities.Any(a => 
		a.AppUser.UserName == _userAccessor.GetCurrentUsername() && a.IsHost));
}

var activities = await queryable
	.Skip(request.Offset ?? 0)
	.Take(request.Limit ?? 3)
	.ToListAsync();
```

**Comment by shadowvzs** [comment]
issue was wth wrong wrong enviroment (not was )  so migration was for the SQLite which is different than MySQL migration

export ASPNETCORE_ENVIRONMENT=Production

**Comment by paulo1988cesar** [comment]
have you got the solution?
i've the same issue.

**Comment by shadowvzs** [comment]
yea, i used wrong environment (SQLLite instead of MySQL) :)

**Comment by paulo1988cesar** [comment]
i still no able to make this work. My environment is correct, but the app doesn't work, still have the same problem. I guess that is something related with the new versions of EntityFrameworkCore.
I tried to change for sql server, but the migrations doens't go well. I'll finish the course without this. thks

**Comment by shadowvzs** [comment]
you must check 3 place, in appSettings.json or how it is called there have envirnment and also in your os (ex. digitial ocean or locally environment) and in startup.cs if it detect the right db server
i noted down here ~every step
https://github.com/shadowvzs/reactivities/blob/master/Doc/Command_History.txt
